let questions =[
    {question: "Какой земной полюс холоднее?", 
    rightAnswer: "Южный полюс", 
    wrongAnswer1:"Северный полюс" , 
    wrongAnswer2:"Они имеют одинаковую температуру",
    wrongAnswer3:"Лунный полюс"},
    {question: "Какие из океанских существ самые шумные?", 
    rightAnswer: "Креветки", 
    wrongAnswer1:"Акулы" , 
    wrongAnswer2:"Рыбы",
    wrongAnswer3:"Крабы"},
    {question: "На какой планете солнечной системы находится самая высокая гора?", 
    rightAnswer: "На Марсе", 
    wrongAnswer1:"На Венере" , 
    wrongAnswer2:"На Земле",
    wrongAnswer3:"На Юпитере"},
    {question: "Сколько глаз у безглазого большеглазого паука?", 
    rightAnswer: "Нет глаз", 
    wrongAnswer1:"Один большой глаз, который не работает" , 
    wrongAnswer2:"Два больших глаза",
    wrongAnswer3:"Восемь глаз"},
    {question: "Что из этого является китайским изобретением?", 
    rightAnswer: "Чоп суи", 
    wrongAnswer1:"Стекло" , 
    wrongAnswer2:"Рикша",
    wrongAnswer3:"Печенье с предсказанием"},
    {question: "Что из этого имеет самую большую площадь?", 
    rightAnswer: "Центральный парк в Нью-Йорке", 
    wrongAnswer1:"Княжество Монако" , 
    wrongAnswer2:"Ватикан",
    wrongAnswer3:"Все одинаковой площади"},
    {question: "Самая дорогая специя в мире?", 
    rightAnswer: "Шафран", 
    wrongAnswer1:"Кориандр" , 
    wrongAnswer2:"Сумах",
    wrongAnswer3:"Пыльца фенхеля"},
    {question: "Какая из этих птиц может летать задом наперед?", 
    rightAnswer: "Колибри", 
    wrongAnswer1:"Воробей" , 
    wrongAnswer2:"Лесной сыч",
    wrongAnswer3:"Палила"},
]